bounceback: true
teleport_entities: true
send_no_destination_message: true
send_disabled_portal_message: true
portal-auto-link-when:
  nether:
    prefix: ''
    suffix: _nether
  end:
    prefix: ''
    suffix: _the_end
worlds:
  world_survival:
    portalgoesto:
      NETHER: world_nether
  world_nether:
    portalgoesto:
      NETHER: world_survival
