#
#      
#      ░██████╗██╗░░░██╗██████╗░██████╗░███████╗███╗░░░███╗███████╗
#      ██╔════╝██║░░░██║██╔══██╗██╔══██╗██╔════╝████╗░████║██╔════╝
#      ╚█████╗░██║░░░██║██████╔╝██████╔╝█████╗░░██╔████╔██║█████╗░░
#      ░╚═══██╗██║░░░██║██╔═══╝░██╔══██╗██╔══╝░░██║╚██╔╝██║██╔══╝░░
#      ██████╔╝╚██████╔╝██║░░░░░██║░░██║███████╗██║░╚═╝░██║███████╗
#      ╚═════╝░░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░░░░╚═╝╚══════╝
#
#          ░██████╗███████╗████████╗██╗░░░██╗██████╗░░██████╗
#          ██╔════╝██╔════╝╚══██╔══╝██║░░░██║██╔══██╗██╔════╝
#          ╚█████╗░█████╗░░░░░██║░░░██║░░░██║██████╔╝╚█████╗░
#          ░╚═══██╗██╔══╝░░░░░██║░░░██║░░░██║██╔═══╝░░╚═══██╗
#          ██████╔╝███████╗░░░██║░░░╚██████╔╝██║░░░░░██████╔╝
#          ╚═════╝░╚══════╝░░░╚═╝░░░░╚═════╝░╚═╝░░░░░╚═════╝░
#                                           Survival Setup
#

#exampletitle:
#  title: 'Example title' #Head title
#  subtitle: 'Example sub title' #Sub title
#  fadein: 20 #fade-in time in ticks
#  staytime: 40 #stay-time in ticks
#  fadeout: 20 #fade-out time in ticks

#  _____ _             _   _                  _   _ _   _           
# |  ___| |_   _      | |_(_)_ __ ___   ___  | |_(_) |_| | ___  ___ 
# | |_  | | | | |_____| __| | '_ ` _ \ / _ \ | __| | __| |/ _ \/ __|
# |  _| | | |_| |_____| |_| | | | | | |  __/ | |_| | |_| |  __/\__ \
# |_|   |_|\__, |      \__|_|_| |_| |_|\___|  \__|_|\__|_|\___||___/
#          |___/
#

flytime15:
  title: '&r'
  subtitle: '&e+15 minutes'
  fadein: 20
  staytime: 40
  fadeout: 20
flytime30:
  title: '&r'
  subtitle: '&e+30 minutes'
  fadein: 20
  staytime: 40
  fadeout: 20
flytime45:
  title: '&r'
  subtitle: '&e+45 minutes'
  fadein: 20
  staytime: 40
  fadeout: 20
flytime60:
  title: '&r'
  subtitle: '&e+60 minutes'
  fadein: 20
  staytime: 40
  fadeout: 20
flytime6h:
  title: '&r'
  subtitle: '&e+6 hours'
  fadein: 20
  staytime: 40
  fadeout: 20
flytime24h:
  title: '&r'
  subtitle: '&e+24 hours'
  fadein: 20
  staytime: 40
  fadeout: 20

#  ____                                       ____           _      
# / ___| _   _ _ __  _ __ ___ _ __ ___   ___ / ___|   _  ___| | ___ 
# \___ \| | | | '_ \| '__/ _ \ '_ ` _ \ / _ \ |  | | | |/ __| |/ _ \
#  ___) | |_| | |_) | | |  __/ | | | | |  __/ |__| |_| | (__| |  __/
# |____/ \__,_| .__/|_|  \___|_| |_| |_|\___|\____\__, |\___|_|\___|
#             |_|                                 |___/

goodmorning:
  title: '&r'
  subtitle: '&eGoodmorning!'
  fadein: 20
  staytime: 45
  fadeout: 20

#  _  ___ _                           _             _   _ _   _      
# | |/ (_) |_ ___   _ __ ___  ___ ___(_)_   _____  | |_(_) |_| | ___ 
# | ' /| | __/ __| | '__/ _ \/ __/ _ \ \ \ / / _ \ | __| | __| |/ _ \
# | . \| | |_\__ \ | | |  __/ (_|  __/ |\ V /  __/ | |_| | |_| |  __/
# |_|\_\_|\__|___/ |_|  \___|\___\___|_| \_/ \___|  \__|_|\__|_|\___|
#                                                                    

kitreceived:
  title: '&r'
  subtitle: '&2✠ &a&lKit received! &r&2✠'
  fadein: 10
  staytime: 30
  fadeout: 15

#  ____                                      _   _ _   _      
# |  _ \__   ___ __    _______  _ __   ___  | |_(_) |_| | ___ 
# | |_) \ \ / / '_ \  |_  / _ \| '_ \ / _ \ | __| | __| |/ _ \
# |  __/ \ V /| |_) |  / / (_) | | | |  __/ | |_| | |_| |  __/
# |_|     \_/ | .__/  /___\___/|_| |_|\___|  \__|_|\__|_|\___|
#             |_|                                             

pvpzone:
  title: '&c&lPvP Zone'
  subtitle: '&7Item Drop Enabled'
  fadein: 10
  staytime: 30
  fadeout: 5

#  ____                                       _   _ _   _           
# |  _ \ _   _ _ __   __ _  ___  ___  _ __   | |_(_) |_| | ___  ___ 
# | | | | | | | '_ \ / _` |/ _ \/ _ \| '_ \  | __| | __| |/ _ \/ __|
# | |_| | |_| | | | | (_| |  __/ (_) | | | | | |_| | |_| |  __/\__ \
# |____/ \__,_|_| |_|\__, |\___|\___/|_| |_|  \__|_|\__|_|\___||___/
#                    |___/

dungeons-world:
  title: '&e&lDungeons'
  subtitle: '&r'
  fadein: 10
  staytime: 30
  fadeout: 5  
dungeons-area_01:
  title: '&7⤛｛ I ｝⤜'
  subtitle: '&e&lBreaking the Shields'
  fadein: 10
  staytime: 20
  fadeout: 5
dungeons-area_02:
  title: '&7⤛｛ II ｝⤜'
  subtitle: '&e&lThe Abandoned Mines'
  fadein: 10
  staytime: 20
  fadeout: 5
dungeons-area_03:
  title: '&7⤛｛ III ｝⤜'
  subtitle: '&e&lEmotional Tolls'
  fadein: 10
  staytime: 20
  fadeout: 5
dungeons-area_04:
  title: '&7⤛｛ IV ｝⤜'
  subtitle: '&e&lSeeking a Fortune'
  fadein: 10
  staytime: 20
  fadeout: 5
dungeons-area_05:
  title: '&7⤛｛ V ｝⤜'
  subtitle: '&e&lName - 05'
  fadein: 10
  staytime: 20
  fadeout: 5

#  ____                                       ___                  _       
# / ___| _   _ _ __  _ __ ___ _ __ ___   ___ / _ \ _   _  ___  ___| |_ ___ 
# \___ \| | | | '_ \| '__/ _ \ '_ ` _ \ / _ \ | | | | | |/ _ \/ __| __/ __|
#  ___) | |_| | |_) | | |  __/ | | | | |  __/ |_| | |_| |  __/\__ \ |_\__ \
# |____/ \__,_| .__/|_|  \___|_| |_| |_|\___|\__\_\\__,_|\___||___/\__|___/
#             |_|

anti-cheat-quests-first:
  title: '&c⚠'
  subtitle: '&r'
  fadein: 5
  staytime: 15
  fadeout: 5
anti-cheat-quests-second:
  title: '&c⚠'
  subtitle: '&cSecond warning!'
  fadein: 5
  staytime: 15
  fadeout: 5
anti-cheat-quests-last:
  title: '&c⚠'
  subtitle: '&cLast warning!'
  fadein: 5
  staytime: 15
  fadeout: 5